name: manager_game_frontend
description: A new Flutter project for Manager Game.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  provider: ^6.1.1
  supabase_flutter: ^2.0.2
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
