name: manager_game_frontend
description: A new Flutter project for Manager Game.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  web_socket_channel: ^3.0.1
  provider: ^6.1.1
  supabase_flutter: ^2.0.2
  http: ^1.2.0
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  flutter_animate: ^4.5.1
  shadcn_ui: ^0.46.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  audioplayers: ^6.0.0
  collection: ^1.18.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
